name: release
on:
  push:
    branches:
      - main
      - '[0-9]+.[0-9]+.x'
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
  GITHUB_PAGES_BRANCH: gh_pages

defaults:
  run:
    shell: bash

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [stable-x86_64-unknown-linux-gnu]
    steps:
      - uses: actions/checkout@master
      - run: rustup toolchain install ${{ matrix.target }}
      - name: Log in to Buf registry
        env:
          BUF_TOKEN: ${{ secrets.BUF_TOKEN }}
        run: |
          cargo login --registry buf "Bearer $BUF_TOKEN"
      - run: cargo +${{ matrix.target }} build --release